### ISSUE TITLE
minor issue regarding bracket being ) instead of } in tail example website

### ISSUE THREAD

**Issue by Dragonearuss** [MrSirSquishy/SquishyAPI#3]
![image](https://github.com/MrSirSquishy/SquishyAPI/assets/147288202/fd8c1be5-e971-4543-8e5d-f2eb0fefb43e)

https://mrsirsquishy.notion.site/Squishy-API-Guide-3e72692e93a248b5bd88353c96d8e6c5?p=e28108029eb346cf85048f7ed3f643e0&pm=c

tail example actually needs } to end, not )
super minor

**Comment by MrSirSquishy** [comment]
you're always good at finding the small things I can never find
